
export type DayOfWeek = 'Thứ 2' | 'Thứ 3' | 'Thứ 4' | 'Thứ 5' | 'Thứ 6' | 'Thứ 7' | 'Chủ Nhật';
export const ALL_DAYS_OF_WEEK: DayOfWeek[] = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ Nhật'];

export type PaymentCycle = '1 tháng' | '8 buổi' | '10 buổi' | 'Theo ngày';
export const ALL_PAYMENT_CYCLES: PaymentCycle[] = ['1 tháng', '8 buổi', '10 buổi', 'Theo ngày'];

export type PaymentMethod = 'Tiền mặt' | 'Chuyển khoản' | 'Khác';
export const ALL_PAYMENT_METHODS: PaymentMethod[] = ['Tiền mặt', 'Chuyển khoản', 'Khác'];

export interface LopHoc {
  id: string;
  tenLop: string;
  lichHoc: DayOfWeek[];
  gioHoc: string; // e.g., "18:00 - 19:30"
  diaDiem: string;
  hocPhi: number;
  chuKyDongPhi: PaymentCycle;
  soHocSinhHienTai: number;
  trangThai: 'Đang hoạt động' | 'Đã đóng';
  ngayDongLop?: string; // YYYYMMDD format
}

export type PaymentStatus = 'Đã thanh toán' | 'Chưa thanh toán' | 'Quá hạn';

export interface HocSinh {
  id: string; // Mã HS: YYYYXXXX
  hoTen: string;
  ngaySinh: string; // ISO Date string
  diaChi: string;
  soDienThoai?: string;
  lopId: string;
  tenLop?: string; // Denormalized for display
  ngayDangKy: string; // ISO Date string
  chuKyThanhToan: PaymentCycle;
  tinhTrangThanhToan: PaymentStatus;
  ngayThanhToanGanNhat?: string; // ISO Date string
  soBuoiDaHocTrongChuKy?: number; // For session-based cycles
}

export interface HocPhiGhiNhan {
  id: string; // Tự động tạo khi ghi nhận
  hocSinhId: string;
  hocSinhTen?: string; // Denormalized
  lopId?: string;
  lopTen?: string; // Denormalized
  ngayThanhToan: string; // ISO Date string, from form
  soTienDaDong: number; // from form
  soTienTheoChuKy: number; // expected tuition fee for the cycle
  phuongThucThanhToan: PaymentMethod; // from form
  chuKyDongPhi: PaymentCycle; // from student/class
  ghiChu?: string; // from form
  hoaDonSo?: string; // Tự động tạo dạng YYYY-XXXX
}


export type AttendanceStatus = 'Có mặt' | 'Vắng mặt' | 'GV nghỉ' | 'Học bù';
export const ALL_ATTENDANCE_STATUSES: AttendanceStatus[] = ['Có mặt', 'Vắng mặt', 'GV nghỉ', 'Học bù'];

export interface DiemDanhGhiNhan {
  id: string; // Auto-generated when recording
  hocSinhId: string;
  lopId: string;
  ngayDiemDanh: string; // ISO Date string (YYYYMMDD)
  trangThai: AttendanceStatus;
  ghiChu?: string;
  // Add hoTen and tenLop for modal display if needed directly from this record
  hoTen?: string; // Denormalized student name
  tenLop?: string; // Denormalized class name
}


export type MakeupClassStatus = 'chờ xếp lịch' | 'đã xếp lịch' | 'đã hoàn thành' | 'đã hủy';
export const ALL_MAKEUP_CLASS_STATUSES: MakeupClassStatus[] = ['chờ xếp lịch' , 'đã xếp lịch' , 'đã hoàn thành' , 'đã hủy'];


export interface GiaoVienVangRecord {
  id: string; // Auto-generated
  classId: string;
  className: string; // Denormalized for easier display
  originalDate: string; // YYYYMMDD format
  status: MakeupClassStatus;
  makeupDate?: string; // YYYYMMDD format, if scheduled
  makeupTime?: string; // e.g., "18:00 - 19:30", if scheduled
  notes?: string;
  createdAt: string; // ISO Date string
}

export type HomeworkStatus = 'Có làm đầy đủ' | 'Chỉ làm 1 phần' | 'Không có làm' | '';
export const ALL_HOMEWORK_STATUSES: HomeworkStatus[] = ['Có làm đầy đủ', 'Chỉ làm 1 phần', 'Không có làm'];


export interface TestScoreRecord {
  id?: string; // Auto-generated by Firestore upon saving
  studentId: string;
  studentName?: string; // Denormalized
  classId: string;
  className?: string; // Denormalized
  testDate: string; // ISO Date string (e.g., YYYY-MM-DD)
  testName?: string; // Made optional
  score?: number;
  masteredLesson: boolean; // "Đã thuộc bài" (true) or "Không thuộc bài" (false)
  vocabularyToReview?: string; // "Từ vựng cần học lại"
  generalRemarks?: string; // Other general remarks from teacher
  homeworkStatus?: HomeworkStatus; // Added
  createdAt?: string; // ISO string for client-side
  updatedAt?: string; // ISO string for client-side
}

// Helper type for the form state on KiemTraPage
export type StudentScoreInput = Omit<TestScoreRecord, 'id' | 'studentId' | 'studentName' | 'classId' | 'className' | 'testDate' | 'testName' | 'score' | 'createdAt' | 'updatedAt'> & {
  score?: number | string; // Allow string for input flexibility, convert to number on save
};
