
"use client";

import { useState } from 'react';
import { PlusCircle, Filter, Edit, Trash2, UserPlus, RefreshCw } from 'lucide-react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import AddClassForm from '@/components/lop-hoc/AddClassForm';
import ClassCard from '@/components/lop-hoc/ClassCard';
import type { LopHoc } from '@/lib/types';
import { TEXTS_VI } from '@/lib/constants';
import DashboardLayout from '../dashboard-layout';
import { useToast } from '@/hooks/use-toast';
import { getClasses, addClass, updateClass, deleteClass } from '@/services/lopHocService';
import { generateId } from '@/lib/utils';
import { Skeleton } from '@/components/ui/skeleton';

export default function LopHocPage() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingClass, setEditingClass] = useState<LopHoc | null>(null);

  const { data: classes = [], isLoading, isError, error } = useQuery<LopHoc[], Error>({
    queryKey: ['classes'],
    queryFn: getClasses,
  });

  const addClassMutation = useMutation({
    mutationFn: (newClassData: Omit<LopHoc, 'id' | 'soHocSinhHienTai' | 'trangThai'>) => {
      const classId = generateId('lop_');
      return addClass(newClassData, classId);
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['classes'] });
      toast({
        title: "Thêm lớp thành công!",
        description: `Lớp "${data.tenLop}" đã được thêm vào hệ thống.`,
      });
      setIsModalOpen(false);
    },
    onError: (error) => {
      toast({
        title: "Lỗi khi thêm lớp",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const updateClassMutation = useMutation({
    mutationFn: (updatedClass: LopHoc) => {
      const { id, ...dataToUpdate } = updatedClass;
      return updateClass(id, dataToUpdate);
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['classes'] });
      toast({
        title: "Cập nhật thành công!",
        description: `Lớp "${variables.tenLop}" đã được cập nhật.`,
      });
      setIsModalOpen(false);
      setEditingClass(null);
    },
    onError: (error) => {
      toast({
        title: "Lỗi khi cập nhật lớp",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const deleteClassMutation = useMutation({
    mutationFn: deleteClass,
    onSuccess: (_, classId) => {
      queryClient.invalidateQueries({ queryKey: ['classes'] });
      toast({
        title: "Đã xóa lớp học",
        description: `Lớp học với ID ${classId} đã được xóa.`,
      });
    },
    onError: (error) => {
      toast({
        title: "Lỗi khi xóa lớp học",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const handleSubmitClassForm = (data: LopHoc) => {
    if (editingClass) {
      updateClassMutation.mutate(data);
    } else {
      // For add, 'id' is generated by service, 'soHocSinhHienTai' and 'trangThai' are defaulted
      const { id, soHocSinhHienTai, trangThai, ...newClassData } = data;
      addClassMutation.mutate(newClassData);
    }
  };
  
  const handleDeleteClass = (classId: string) => {
    // Add confirmation dialog here in a real app
    deleteClassMutation.mutate(classId);
  };

  const handleOpenEditModal = (lopHoc: LopHoc) => {
    setEditingClass(lopHoc);
    setIsModalOpen(true);
  };
  
  const handleOpenAddModal = () => {
    setEditingClass(null);
    setIsModalOpen(true);
  };

  const handleAddStudentToClass = (classId: string) => {
    alert(`DEBUG from LopHocPage: Adding student to class ${classId}`); // DEBUGGING ALERT
    toast({
      title: "Chức năng đang phát triển",
      description: `Sẵn sàng thêm học sinh vào lớp ${classId}.`,
      variant: "default",
    });
    console.log("Attempting to add student to class from LopHocPage:", classId);
  };

  if (isError) {
    return (
      <DashboardLayout>
        <div className="flex flex-col items-center justify-center h-full text-red-500">
          <p>Lỗi tải danh sách lớp học: {error.message}</p>
          <Button onClick={() => queryClient.invalidateQueries({ queryKey: ['classes'] })} className="mt-4">
            <RefreshCw className="mr-2" /> Thử lại
          </Button>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="container mx-auto py-8 px-4 md:px-6">
        <div className="flex flex-col sm:flex-row justify-between items-center mb-6 gap-4">
          <h1 className="text-3xl font-bold text-foreground">Danh sách Lớp học</h1>
          <div className="flex gap-2">
            <Button variant="outline" size="icon" aria-label="Lọc">
              <Filter />
            </Button>
            <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
              <DialogTrigger asChild>
                <Button onClick={handleOpenAddModal} size="icon" aria-label={TEXTS_VI.addClassTitle}>
                  <PlusCircle />
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[600px]">
                <DialogHeader>
                  <DialogTitle>{editingClass ? TEXTS_VI.editButton + " lớp học" : TEXTS_VI.addClassTitle}</DialogTitle>
                </DialogHeader>
                <AddClassForm 
                  onSubmit={handleSubmitClassForm} 
                  initialData={editingClass}
                  onClose={() => setIsModalOpen(false)}
                  isSubmitting={addClassMutation.isPending || updateClassMutation.isPending}
                />
              </DialogContent>
            </Dialog>
          </div>
        </div>

        {isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[...Array(3)].map((_, i) => (
              <CardSkeleton key={i} />
            ))}
          </div>
        ) : classes.length === 0 ? (
          <div className="text-center py-10 bg-card rounded-lg shadow p-6">
            <p className="text-xl text-muted-foreground">{TEXTS_VI.noClassesFound}</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {classes.map((lopHoc) => (
              <ClassCard 
                key={lopHoc.id} 
                lopHoc={lopHoc} 
                onEdit={() => handleOpenEditModal(lopHoc)}
                onDelete={() => handleDeleteClass(lopHoc.id)}
                onAddStudent={handleAddStudentToClass} 
              />
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}

const CardSkeleton = () => (
  <div className="flex flex-col space-y-3 p-4 border rounded-lg shadow">
    <Skeleton className="h-6 w-3/4" />
    <Skeleton className="h-4 w-1/2" />
    <div className="space-y-2 pt-2">
      <Skeleton className="h-4 w-full" />
      <Skeleton className="h-4 w-5/6" />
      <Skeleton className="h-4 w-full" />
    </div>
    <div className="flex gap-2 pt-4 border-t mt-auto">
      <Skeleton className="h-8 w-1/3" />
      <Skeleton className="h-8 w-1/3" />
      <Skeleton className="h-8 w-1/3" />
    </div>
  </div>
);
